### ISSUE TITLE
Axe speed is as fast as hand when mining wooden planks, and logs.

### ISSUE THREAD

**Issue by rainysux** [852DuartePls/MoreCraftingTables#13]
https://github.com/Sinytra/Connector/issues/361 It is specifically for my case, a better nether issue, however I am using connector (fabric mods to forge) the developer had highlighted the problem in this thread and I hope you can fix it if possible :). 
Forge 1.20.1

**Comment by 852DuartePls** [comment]
Hello, first of all, sorry for the inconvenience, would you be so kind as to provide me with the version of the mod you are using? Since if I'm not mistaken, that problem was already resolved since version 5.0.2

![image](https://github.com/852DuartePls/MoreCraftingTables/assets/73360977/1b1047c6-c0fc-412c-9527-4b179de399b7)

**Comment by 852DuartePls** [comment]
Sorry for the inconvenience, I have updated the tags and it should now work correctly

[1.20.1 More Crafting Tables 5.1.1](https://legacy.curseforge.com/minecraft/mc-mods/more-crafting-tables-for-forge/download/4786212)

**Comment by rainysux** [comment]
Its no problem at all. I was using the recent version of the mod!

**Comment by rainysux** [comment]
Thank you for your hard work, truly appreciate it, have a good rest of your
week!

**Comment by 852DuartePls** [comment]
Thanks to you too for pointing it out to me, I will be attentive to any future problems that may arise
